### 
# Create User

POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "murphy",
  "name": "Todd Murphy"
}

###
# Create Game

POST http://localhost:3000/games
Content-Type: application/json

{
  "boardWidth": 20,
  "boardHeight": 20,
  "difficulty": 1,
  "userId": "3",
  "durationSeconds": 120,
  "startedAt": "2024-01-09T12:00:00.000Z"
}

###
# Create board

POST http://localhost:3000/boards
Content-Type: application/json

{
  "width": 20,
  "height": 20,
  "difficulty": 1
}


###
# Get all boards

GET http://localhost:3000/boards

###
# Get all users

GET http://localhost:3000/users

###
# Get all games

GET http://localhost:3000/games

###
